project_name: 'my_project'
root_directory: '/Users/james.n.wilson/code/nonwork/repos/automated_project_setup/generated_project'
language: 'python' # [ javascript, python, rust, go ]
system_types: 'path/to/system-types/directory'
domain_types: 'path/to/domain-types/directory'
files:
    - path: 'src/validator'
      methods:
        - 'validate_input(input: Dict) -> Result[DynamoStreamEvent, ErrorMsg]'
    - path: 'src/domains/account'
      methods:
        - 'get_users_for_account(http_client: {requests}, account_ids: List[AccountId]) -> Result[List[User], ErrorMsg]'
        - 'get_account(dynamo: {dynamodb}, id: AccountId) -> Result[Account, ErrorMsg]'
    - path: 'src/domains/user'
      methods:
        - 'update_user(dynamo: {dynamodb}, user_id: UserId) -> Result[List[User], ErrorMsg]'
    - path: 'src/domains/role'
      methods: 
        - 'convert_to_dto(users: List[User]) -> Result[List[TableUsers], ErrorMsg]'
    - path: 'src/cleanup_account_users'
      methods: 
        - 'persist_users(users: List[TableUsers]) -> None'
workflow:
    - validate_input
    - get_users_for_account
    - update_user
    - convert_to_dto
    - persist_users